---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  values:
    controller:
      watchIngressWithoutClass: true
      extraArgs:
        enable-ssl-passthrough: ""
      config:
        use-http2: true
      service:
        type: "LoadBalancer"
        annotations:
          dns.gardener.cloud/dnsnames: "*.tcs.example.com"
          dns.gardener.cloud/ttl: "600"
          dns.gardener.cloud/class: garden
    admissionWebhooks:
      enabled: false
