---
services:
  worker:
    image: ${TCS_IMAGE}
    restart: always
    command: "python3 -m tcsapi.cmd.worker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .worker.env
    network_mode: host
