apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: mariadb
spec:
  chart:
    spec:
      chart: mariadb
      version: "11.5.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: mariadb
  interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
