apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  chart:
    spec:
      chart: rabbitmq
      version: "11.10.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: rabbitmq
  interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
