apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/mariadb
  - ../base/minio
  - ../base/opa
  - ../base/redis
  - ../base/rabbitmq
  - ../base/keycloak
patchesStrategicMerge:
  - mariadb-values.yaml
  - minio-values.yaml
  - opa-values.yaml
  - keycloak-values.yaml
