apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: mariadb
spec:
  values:
    auth:
      rootPassword: password
      database: tcs
      username: tcs
      password: password